### ISSUE TITLE
Alternative approach for keeping track of already discovered legendary locations

### ISSUE THREAD

**Issue by Darxo** [chopeks/mod_find_legendary_maps#1]
I noticed from a quick look into the code that you implemented a backend system for keeping track of legendary locations.

Have you considered an approach where you use the `isDiscovered` state of locations instead in order to quickly on demand find out, which location has not been found yet?

An advantage of this approach is that you can add it mid-game, when you already discovered some locations without this mod present, and ignores them correctly. (Not sure if your mod has a special rule for this implemented)

### Example
```
foreach (s in ::World.EntityManager.getLocations())
{
	if (!s.isLocationType(::Const.World.LocationType.Unique)) continue;
	if (s.isDiscovered()) continue;
	if (s.getVisibilityMult() == 0.0) continue;	 // These legendary locations are not meant to be found yet (tundra_elk_location)

	// s == undiscovered legendary location
}
```

**Comment by chopeks** [comment]
If you consider only the standard option, then the tracker doesn't really matter, because it primarily uses the entity manager for finding spawned locations and picks one of them if no map already pointing to it exists in inventory. This is perfectly safe to add mid-game and the existence of the tracker is meaningless in this state. Checking `isDiscovered()` could potentially help to prioritize undiscovered locations over already discovered, but that's it.

This does change however with experimental option, that attempts to spawn missing locations, where I need to know somehow which locations were already conquered (via tracker), which are spawned (via entity manager) and which are missing (not present in both). Just entity manager is not enough, because locations are removed from it when conquered.

Another reason why I didn't select a fully automatic approach to it is, that unique locations (at least in vanilla) have names set when you discover them (which I consider weird design decision, but we have live with that).
